name = "jiwonz/luau_path"
version = "0.1.2"
description = "A Luau library to handle file paths based on the Rust path library by jeparlefrancais, Uploaded for pesde"
authors = ["jeparlefrancais <jeparlefrancais21@gmail.com>"]
repository = "https://github.com/seaofvoices/luau-path"
license = "MIT"
includes = ["src", "README.md", "LICENSE.txt", "pesde.toml"]

[target]
environment = "luau"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
luau_disk = { name = "jiwonz/luau_disk", version = "^0.1.4" }
